### ISSUE TITLE
Issue with deploying to cloud foundry

### ISSUE THREAD

**Issue by VineethRamakrishnan** [mishk0/slack-bot-api#146]
@mishk0 Have below clarifications needed for deploying node application which uses slackbots module. 
experienced below error when tried to run the node application from cloud foundry. but it worked well when trying to run from local.

```
10:10:40.261: [APP/PROC/WEB.0] > Sample@1.0.0 start /home/vcap/app
10:10:40.261: [APP/PROC/WEB.0] > node index.js
10:10:41.707: [APP/PROC/WEB.0] Error: Error: connect EHOSTUNREACH 13.225.226.153:443
10:10:41.707: [APP/PROC/WEB.0]     at _api.then.fail (/home/vcap/app/node_modules/slackbots/index.js:46:33)
10:10:41.707: [APP/PROC/WEB.0]     at Array.<anonymous> (/home/vcap/app/node_modules/vow/lib/vow.js:773:56)
10:10:41.707: [APP/PROC/WEB.0]     at callFns (/home/vcap/app/node_modules/vow/lib/vow.js:24:35)
10:10:41.707: [APP/PROC/WEB.0]     at process._tickCallback (internal/process/next_tick.js:61:11)
10:10:41.720: [APP/PROC/WEB.0] Exit status 0
10:10:41.723: [CELL/SSHD.0] Exit status 0
10:09:40.717: [API.0] Process has crashed with type: "web"
```

Attached package.json and manifest.yml for reference. 

It would be great if you can help us on this.
[Slack bot.zip](https://github.com/mishk0/slack-bot-api/files/4154212/Slack.bot.zip)

**Comment by alkalinecoffee** [comment]
You might need to enable a proxy in your cloudfoundry instance.
