### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by leonardo-beabr** [mishk0/slack-bot-api#150]
I have an AWS Lambda function with slackbots and in some cases, I receive this error:
{
    "errorType": "Error",
    "errorMessage": "SyntaxError: Unexpected token < in JSON at position 0",
    "stack": [
        "Error: SyntaxError: Unexpected token < in JSON at position 0",
        "    at /var/task/node_modules/slackbots/index.js:46:33",
        "    at Array.<anonymous> (/var/task/node_modules/vow/lib/vow.js:773:56)",
        "    at callFns (/var/task/node_modules/vow/lib/vow.js:24:35)",
        "    at processTicksAndRejections (internal/process/task_queues.js:79:11)"
    ]
}

**Comment by leonardo-beabr** [comment]
In this AWS Lambda function, I changed the number of retries of 0 to 1 and this message didn't appear anymore.
