### ISSUE TITLE
Facing error in connection of uipath and Slack 

### ISSUE THREAD

**Issue by kuldarshan28** [mishk0/slack-bot-api#154]
hello team 
I have watched https://youtu.be/B17pGNJugLs

after creating the slack bot I am unable to trigger the bot from the visual studio as given in your video 
I am facing the following error please help me out 

PS C:\Chatbot> npm start

> chatbot@1.0.0 start
> node index.js

C:\Chatbot\node_modules\vow\lib\vow.js:105
            throw e;
            ^

Error: method_deprecated
    at C:\Chatbot\node_modules\slackbots\index.js:46:33
    at Array.<anonymous> (C:\Chatbot\node_modules\vow\lib\vow.js:773:56)
    at callFns (C:\Chatbot\node_modules\vow\lib\vow.js:24:35)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Bot instance at:
    at C:\Chatbot\node_modules\slackbots\index.js:46:19
    at Array.<anonymous> (C:\Chatbot\node_modules\vow\lib\vow.js:773:56)
    at callFns (C:\Chatbot\node_modules\vow\lib\vow.js:24:35)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
PS C:\Chatbot>

**Comment by kaushalendra-pandey** [comment]
Were you able to resolve it?

**Comment by anishnair02** [comment]
Facing the same issue and it returns the same error as posted by @[kuldarshan28](https://github.com/kuldarshan28)
Any fix to it?

**Comment by Eumorg** [comment]
The same problem. It doesn't work(

**Comment by mishk0** [comment]
Thanks for reporting an issue. Some Slack API calls were deprecated, I've updated them recently. Now it should work, let me know if the issue still persists
