### ISSUE TITLE
Issue with extending bot

### ISSUE THREAD

**Issue by DoumanAsh** [mishk0/slack-bot-api#43]
When calling super() from my child i get following error:
```
E:\Downloads\Git\js\aru-slacky.js\node_modules\vow\lib\vow.js:104
            throw e;
            ^

Error: [Slack Bot Error] undefined
    at assert (E:\Downloads\Git\js\aru-slacky.js\node_modules\slackbots\libs\utils.js:15:15)
    at E:\Downloads\Git\js\aru-slacky.js\node_modules\slackbots\index.js:42:9
    at Array.<anonymous> (E:\Downloads\Git\js\aru-slacky.js\node_modules\vow\lib\vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (E:\Downloads\Git\js\aru-slacky.js\node_modules\vow\lib\vow.js:23:35)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

Not sure if Bot can be extended like that but here is my code:
```
class Aru extends Bot {
    constructor(settings = {}) {
        var name = settings.name || "Aru";
        var token;

        if (settings.token) {
            token = settings.token;
        }
        else if (process.env.ARU_SLACK_TOKEN) {
            token = process.env.ARU_SLACK_TOKEN;
        }
        else {
            throw new Error("No slack API token available");
        }

        super({
            token: token,
            name: name
        });

        this.master = settings.master || "douman";
    }

    /**
     * Run bot.
     */
    launch() {
        this.on('start', function() {
            bot.postMessageToUser(this.master, 'Good day, master!');
        });
    }
}
```

It throws when i call ```on```

**Comment by DoumanAsh** [comment]
Sorry, i noticed bad copy-paste...
I hope no one will run into the same lame mistake
