### ISSUE TITLE
Error: SyntaxError: Unexpected token Y

### ISSUE THREAD

**Issue by rick-rheo** [mishk0/slack-bot-api#88]
Error: SyntaxError: Unexpected token Y
    at /opt/agent/server/node_modules/slackbots/index.js:42:33
    at Array.<anonymous> (/opt/agent/server/node_modules/slackbots/node_modules/vow/lib/vow.js:754:56)

Just using it

**Comment by rick-rheo** [comment]
More Info

`slack = new slackBot({
	token: Config.slack.token,
	name:  'Bot'
});

console.log('Slack starting');
slack.on('start', () => {
	console.log('Slack started');
});`

outputs

`Slack starting 

Error: SyntaxError: Unexpected token Y
    at /opt/agent/server/node_modules/slackbots/index.js:42:33
    at Array.<anonymous> (/opt/agent/server/node_modules/slackbots/node_modules/vow/lib/vow.js:754:56)
    at Immediate.callFns [as _onImmediate] (/opt/agent/server/node_modules/slackbots/node_modules/vow/lib/vow.js:24:35)
    at processImmediate [as _immediateCallback] (timers.js:396:17) 
`

This happens in AWS when a new instance is brought up and runs the above code.

**Comment by bryjch** [comment]
Recently just encountered this error too - not sure if it's the same reason, but I believe I was hitting the Slack rate limit similar to #56. 
Does it happen to you immediately when running your app, or after restarting it many times?
After chilling for a couple minutes and restarting my app it seems fine.

**Comment by rick-rheo** [comment]
This was because of the rate limit.   Still... this library shouldn't crash when it gets a non-json response.
