### ISSUE TITLE
Change rtm.start to rtm.connect 

### ISSUE THREAD

**Issue by smathews** [mishk0/slack-bot-api#96]
see https://github.com/slackapi/python-slackclient/issues/190

"On very large Slack teams, the rtm.start payload can be too large to deliver before a timeout (server timeouts would return response 500, but also the websocket URL itself is short-lived so the timeout could be from the time it takes for the client to read the response)."

The error presents itself in slackbots as:
```/usr/src/app/node_modules/vow/lib/vow.js:105
            throw e;
            ^

Error: [Slack Bot Error] undefined
    at assert (/usr/src/app/node_modules/slackbots/libs/utils.js:15:15)
    at /usr/src/app/node_modules/slackbots/index.js:42:9
    at Array.<anonymous> (/usr/src/app/node_modules/vow/lib/vow.js:754:56)
    at Immediate.callFns (/usr/src/app/node_modules/vow/lib/vow.js:24:35)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)```

**Comment by mpaz-redstage** [comment]
how to fix?
